@startuml pert5

left to right direction

actor User as "User"

rectangle "Source code pert4" {
    usecase "Call void Tambah" as tambah
    usecase "Call void Kurang" as kurang
    usecase "Call void Bagi" as bagi
    usecase "Call void Kali" as kali
    usecase "Exit" as exit
    } 

    User --> Input  
    input --> menu : Choice Menu
    menu --> tambah
    tambah --> exit

    User --> Input  
    input --> menu : Choice Menu
    menu --> kurang
    kurang --> exit

    User --> Input  
    input --> menu : Choice Menu
    menu --> kali
    kali --> exit

    User --> Input  
    input --> menu : Choice Menu
    menu --> bagi
    bagi --> exit

    @enduml